[package]
name = "rust-backend"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rust-backend"
path = "src/main.rs"
test = false
bench = false

[dependencies]
axum = "0.7.5"
hyper = { version = "1.4.1", features = ["full"] }
tokio = { version = "1.40.0", features = ["full"] }
tower = "0.5.1"
